-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin
(
    id_admin character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nama character(100) COLLATE pg_catalog."default" NOT NULL,
    alamat character varying(100) COLLATE pg_catalog."default" NOT NULL,
    kecamatan character varying(100) COLLATE pg_catalog."default" NOT NULL,
    kabupaten character varying(100) COLLATE pg_catalog."default" NOT NULL,
    no_hp character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT admin_pkey PRIMARY KEY (id_admin)
);

CREATE TABLE IF NOT EXISTS public.administrasi
(
    id_administrasi character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tgl_keluar date NOT NULL,
    pasien_no_rm integer NOT NULL,
    admin_id_admin character varying(100) COLLATE pg_catalog."default" NOT NULL,
    biaya_kamar integer NOT NULL,
    total_obat integer NOT NULL,
    total_tindakan integer NOT NULL,
    pembayaran_id_pembayaran character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "no_bpjs/no_rek" character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT administrasi_pkey PRIMARY KEY (id_administrasi)
);

CREATE TABLE IF NOT EXISTS public.detail_obat
(
    id_detail_obat character varying(100) COLLATE pg_catalog."default" NOT NULL,
    pasien_no_rm integer NOT NULL,
    obat_id_obat character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT detail_obat_pkey PRIMARY KEY (id_detail_obat)
);

CREATE TABLE IF NOT EXISTS public.detail_tindakan
(
    id_det_tdkn character varying(100) COLLATE pg_catalog."default" NOT NULL,
    pasien_no_rm integer NOT NULL,
    dokter_id_dokter character varying(100) COLLATE pg_catalog."default" NOT NULL,
    perawat_id_perawat character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tindakan_id_tindakan character varying(100) COLLATE pg_catalog."default" NOT NULL,
    banyak character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT detail_tindakan_pkey PRIMARY KEY (id_det_tdkn)
);

CREATE TABLE IF NOT EXISTS public.dokter
(
    id_dokter character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nama character(100) COLLATE pg_catalog."default" NOT NULL,
    alamat character varying(100) COLLATE pg_catalog."default" NOT NULL,
    kecamatan character varying(100) COLLATE pg_catalog."default" NOT NULL,
    kabupaten character varying(100) COLLATE pg_catalog."default" NOT NULL,
    no_hp character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT dokter_pkey PRIMARY KEY (id_dokter)
);

CREATE TABLE IF NOT EXISTS public.obat
(
    id_obat character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nama_obat character varying(100) COLLATE pg_catalog."default" NOT NULL,
    harga character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT obat_pkey PRIMARY KEY (id_obat)
);

CREATE TABLE IF NOT EXISTS public.pasien
(
    no_rm integer NOT NULL,
    nama character(100) COLLATE pg_catalog."default" NOT NULL,
    tgl_lahir date NOT NULL,
    alamat character varying(100) COLLATE pg_catalog."default" NOT NULL,
    kecamatan character varying(100) COLLATE pg_catalog."default" NOT NULL,
    kabupaten character varying(100) COLLATE pg_catalog."default" NOT NULL,
    no_hp character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pasien_pkey PRIMARY KEY (no_rm)
);

CREATE TABLE IF NOT EXISTS public.pembayaran
(
    id_pembayaran character varying(100) COLLATE pg_catalog."default" NOT NULL,
    via character(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pembayaran_pkey PRIMARY KEY (id_pembayaran)
);

CREATE TABLE IF NOT EXISTS public.perawat
(
    id_perawat character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nama character(100) COLLATE pg_catalog."default" NOT NULL,
    alamat character varying(100) COLLATE pg_catalog."default" NOT NULL,
    kecamatan character varying(100) COLLATE pg_catalog."default" NOT NULL,
    kabupaten character varying(100) COLLATE pg_catalog."default" NOT NULL,
    no_hp character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT perawat_pkey PRIMARY KEY (id_perawat)
);

CREATE TABLE IF NOT EXISTS public.registrasi
(
    id_registrasi character varying(100) COLLATE pg_catalog."default" NOT NULL,
    tgl_masuk date NOT NULL,
    pasien_no_rm integer NOT NULL,
    admin_id_admin character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ruangan_id_ruangan character varying(100) COLLATE pg_catalog."default" NOT NULL,
    keterangan character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT registrasi_pkey PRIMARY KEY (id_registrasi)
);

CREATE TABLE IF NOT EXISTS public.ruangan
(
    id_ruangan character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nama_ruangan character varying(100) COLLATE pg_catalog."default" NOT NULL,
    harga character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ruangan_pkey PRIMARY KEY (id_ruangan)
);

CREATE TABLE IF NOT EXISTS public.tindakan
(
    id_tindakan character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nama_tindakan character(100) COLLATE pg_catalog."default" NOT NULL,
    harga character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tindakan_pkey PRIMARY KEY (id_tindakan)
);

ALTER TABLE IF EXISTS public.administrasi
    ADD CONSTRAINT administrasi_admin_fk FOREIGN KEY (admin_id_admin)
    REFERENCES public.admin (id_admin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.administrasi
    ADD CONSTRAINT administrasi_pasien_fk FOREIGN KEY (pasien_no_rm)
    REFERENCES public.pasien (no_rm) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.administrasi
    ADD CONSTRAINT administrasi_pembayaran_fk FOREIGN KEY (pembayaran_id_pembayaran)
    REFERENCES public.pembayaran (id_pembayaran) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detail_obat
    ADD CONSTRAINT detail_obat_obat_fk FOREIGN KEY (obat_id_obat)
    REFERENCES public.obat (id_obat) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detail_obat
    ADD CONSTRAINT detail_obat_pasien_fk FOREIGN KEY (pasien_no_rm)
    REFERENCES public.pasien (no_rm) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detail_tindakan
    ADD CONSTRAINT detail_tindakan_dokter_fk FOREIGN KEY (dokter_id_dokter)
    REFERENCES public.dokter (id_dokter) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detail_tindakan
    ADD CONSTRAINT detail_tindakan_pasien_fk FOREIGN KEY (pasien_no_rm)
    REFERENCES public.pasien (no_rm) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detail_tindakan
    ADD CONSTRAINT detail_tindakan_perawat_fk FOREIGN KEY (perawat_id_perawat)
    REFERENCES public.perawat (id_perawat) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detail_tindakan
    ADD CONSTRAINT detail_tindakan_tindakan_fk FOREIGN KEY (tindakan_id_tindakan)
    REFERENCES public.tindakan (id_tindakan) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registrasi
    ADD CONSTRAINT registrasi_admin_fk FOREIGN KEY (admin_id_admin)
    REFERENCES public.admin (id_admin) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registrasi
    ADD CONSTRAINT registrasi_pasien_fk FOREIGN KEY (pasien_no_rm)
    REFERENCES public.pasien (no_rm) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.registrasi
    ADD CONSTRAINT registrasi_ruangan_fk FOREIGN KEY (ruangan_id_ruangan)
    REFERENCES public.ruangan (id_ruangan) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;